### ISSUE TITLE
On this page right nav scrolls off page

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/target-developers#29]
Issue in /src/pages/implement/server-side/sdk-guides/best-practices/index.md

When scrolling low on a page the right in-page nav scrolls out of view.
Normal:
![image](https://user-images.githubusercontent.com/15110344/170362167-48c127f8-f71e-4b18-a315-c4ffe47a4f49.png)
Scrolled off:
![image](https://user-images.githubusercontent.com/15110344/170362233-70c3e8d9-3969-4b34-bd78-4f70bae357aa.png)

**Comment by judy-kim** [comment]
It looks kinda wonky, but this is the expected behavior: each item in the right nav becomes selected (black) as you scroll down the page, and eventually, when you reach the bottom of the page / scroll past the final header, the right nav likewise scrolls up out of view. It's easier to see the behavior on a page that has more items in the right nav, such as [this one](https://developer-stage.adobe.com/target/implement/server-side/transition-from-target-legacy-apis/). Similar behavior occurs on Experience League.
