### ISSUE TITLE
link under getting started : "To see how you can get started with the .NET SDK, navigate to the .NET SDK Getting Started Guide." - that points to https://developer-stage.adobe.com/target/implement/server-side/sdk-guides/getting-started/net.md doesn't work

### ISSUE THREAD

**Issue by vishalwani** [AdobeDocs/target-developers#82]
Issue in /src/pages/implement/server-side/net/index.md

1. has two issues: loads in the same page instead of opening a new tab. 
2. https://developer-stage.adobe.com/target/implement/server-side/sdk-guides/getting-started/net.md - loads a blank page.

**Comment by judy-kim** [comment]
Similar issue occurs on 4 total pages due to consolidation of 4 previous SDK "getting started" guides into a single SDK "getting started" guide.

/src/pages/implement/server-side/net/index.md
/src/pages/implement/server-side/java/index.md
/src/pages/implement/server-side/node-js/index.md
/src/pages/implement/server-side/python/index.md

Issue fixed in all 4 pages; link on each of those pages now points to the single consolidated "getting started" guide.
